#!/bin/sh

# This install script creates the appropriate css & js element files necessary
# for the template.  It will look for the INSTALL_TYPE setting from mgiconfig.  
# If this is set to dev the non-minified css and js element files will be used.
# INSTALL_TYPE can be overridden by using adding a command-line argument, i.e.
# "Install dev".  If INSTALL_TYPE is not dev, the minified element files are
# used and the appropriate js and css files are concatenated and minified to 
# the filemanes designated by the TEMPLATE_CSS_FILE, TEMPLATE_JS_FILE,
# HOMEPAGE_CSS_FILE, and HOMEPAGE_JS_FILE parameters set in GlobalConfig.


# generate and source GlobalConfig sh file
/usr/local/mgi/live/lib/python/Configuration.py config/GlobalConfig sh > .Configuration.sh
. .Configuration.sh
rm .Configuration.sh

# cleanup element files
echo "Cleanup css element"
rm template/elements/css.element

if [ $# -gt 0 ]
then
    # test dev build & write dev css and js element files, otherwise
    # write default css and js element files and cat and minify them
    if [ $1 = "dev" ]
    then
        echo "Copy dev css element"
        cp template/elements/cssDev.element template/elements/css.element
    fi   
else
    echo "Copy default css element"
    cp template/elements/cssDefault.element template/elements/css.element
    
    # clean out old minified css files
    echo "Clean up css files"
    rm ./css/$TEMPLATE_CSS_FILE
    rm ./css/$MGIHOME_CSS_FILE
    
    # minify css files
    echo "Generate css files"
    cat ./css/mgi.css ./css/template.css ./css/yui_overrides.css | java -jar yuicompressor-2.4.2.jar --type css > ./css/$TEMPLATE_CSS_FILE
    cat ./css/ajaxtabs.css ./css/homepages.css | java -jar yuicompressor-2.4.2.jar --type css > ./css/$MGIHOME_CSS_FILE        
fi

# clean out old minified js files
echo "Clean up js files"
rm ./js/$TEMPLATE_JS_FILE
rm ./js/$MGIHOME_JS_FILE

# minify js files
echo "Generate js files"
catReplace.py ./js/mgi.txt > ./js/mgi.js
cat ./js/overlib*.js ./js/mgi.js | java -jar yuicompressor-2.4.2.jar --type js > ./js/$TEMPLATE_JS_FILE
cat ./js/ajaxtabs.js |  java -jar yuicompressor-2.4.2.jar --type js > ./js/$MGIHOME_JS_FILE 
